---
title:  "Modelo Pruebas por Dia"
author: "Rene Gutierrez"
date:   "5/5/2020"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(data.table)
library(ggplot2)
```

### Coronavisrus Tracker Mexico

# Analisis
 
## Modelo de Pruebas por Dia

```{r Datos}
datJNSD <- "2020-03-23"
lim     <- 28 
newDat <- allDat[FECHA_INGRESO >= datJNSD,
                 .N,
       by = .(FECHA_ACTUALIZACION, FECHA_INGRESO)][
         , s := FECHA_ACTUALIZACION - FECHA_INGRESO][
           order(FECHA_INGRESO)][
         , .(FECHA_INGRESO, N, s)]
newDat <- dcast(newDat, FECHA_INGRESO ~ s, value.var = "N")
nObs   <- as.matrix(newDat[,2:(lim+2)])
### Value for n
maxTest <- allDat[FECHA_INGRESO >= datJNSD & FECHA_ACTUALIZACION == datTod,
                  .N,
                  by = .(FECHA_INGRESO)][order(FECHA_INGRESO)][,N]
## Number of Periods
m                          <- nrow(nObs)
nObs[1:(m - lim), lim + 1] <- maxTest[1:(m - lim)]
n      <- nObs
```

```{r Simulation Model 1}
# Set-Up
## n Initialization
n <- nObs
## Number of Periods
m <- nrow(nObs)
## Number of Simulations
sim <- 10000
## Samples
ss <- matrix(data = NA, nrow = sim, ncol = lim + 1)
sm <- matrix(data = NA, nrow = sim, ncol = lim + 1)
sa <- numeric(sim)
st <- numeric(sim)
sn <- array(data = NA, dim = c(sim, m, lim + 1))
## Chain Initial Values
mu    <- numeric(lim + 1)
sigma <- numeric(lim + 1)
### Value for mu
mu[1]              <- 1/3
mu[2:(lim + 1)]    <- colMeans(n[, 2:(lim + 1)] / n[, 1:lim], na.rm = TRUE)
### Value for sigma
sigma[1]           <- 300^2
sigma[2:(lim + 1)] <- apply(n[, 2:(lim + 1)] - n[, 1:lim], 2, var, na.rm = TRUE)

n[,1] <- maxTest * mu[1]
### # Replaces the Values that are not Missing
n[!is.na(nObs)] <- nObs[!is.na(nObs)] 
for(j in 2:(lim + 1)){
  n[, j] <- n[, j - 1] * mu[j]
}
### # Replaces the Values that are not Missing
n[!is.na(nObs)] <- nObs[!is.na(nObs)]
# MCMC
for(sam in 1:sim){ # For Each Simulation
  ## Estimates n
  ### i from 1 to m and j from 2 to s - 1
  for(j in 2:lim){
      ### # Computes the Variances
      nvar <- 1 / (1 / sigma[j] + mu[j + 1]^2 / sigma[j + 1])
      ### # Computes the means 
      nmea <- mu[j] * n[,j - 1] / sigma[j] + (n[, j + 1] / mu[j + 1]) * mu[j + 1]^2 / sigma[j + 1]
      nmea <- nmea * nvar
      ### # Samples
      nTemp  <- rnorm(m, mean = nmea, sd = sqrt(nvar))
      n[nTemp > 0, j] <- nTemp[nTemp > 0]
      ### # Replaces the Values that are not Missing
      n[!is.na(nObs)] <- nObs[!is.na(nObs)]
      ### # Removes Negatives
      n[n < 0] <- sn[sam - 1,,][n < 0]
  }
  ### i from 1 to m and j = s
  ### # Computes the Variances
  nvar <- 1 / (1 / sigma[lim + 1] + mu[1]^2 / sigma[1])
  ### # Computes the Means
  nmea <- mu[lim + 1] * n[,lim] / sigma[lim + 1] + (n[, 1] / mu[1]) * mu[1]^2 / sigma[1]
  nmea <- nmea * nvar
  ### # Samples
  nTemp  <- rnorm(m, mean = nmea, sd = sqrt(nvar))
  n[nTemp > 0, lim + 1] <- nTemp[nTemp > 0]
  ### # Replaces the Values that are not Missing
  n[!is.na(nObs)] <- nObs[!is.na(nObs)]
  ### i from 1 to m and j = 0
  ### # Computes the Variances
  nvar <- 1 / (1 / sigma[1] + mu[2]^2 / sigma[2])
  ### # Computes the means 
  nmea <- mu[1] * n[,lim + 1] / sigma[1] + (n[, 2] / mu[2]) * mu[2]^2 / sigma[2]
  nmea <- nmea * nvar
  ### # Samples
  nTemp  <- rnorm(m, mean = nmea, sd = sqrt(nvar))
  n[nTemp > 0, 1] <- nTemp[nTemp > 0]
  ### # Replaces the Values that are not Missing
  n[!is.na(nObs)] <- nObs[!is.na(nObs)]
  ### Rounds all the numbers
  n <- round(n)
  ## Stores n
  sn[sam,,] <- n
  ### Tests if there is a 0
  if(prod(n > 0) == 0){
    print("Negative Tests")
  }
  
  ## Estimates mu
  ### Mean of mu
  muMea <- c(sum(n[,1] * n[,lim + 1] / sum(n[,lim + 1]^2)),
             colSums(n[,1:lim] * n[,2:(lim + 1)]) / colSums(n[,1:lim]^2))
  ### Variance of mu
  muVar <- sigma / colSums(n[,1:lim]^2)
  ### Samples mu
  mu <- rnorm(n = lim + 1, mean = muMea, sd = sqrt(muVar))
  ## Stores mu
  sm[sam,] <- mu

  ## Estimates sigma
  ### Shape of Sigma
  sigSha <- m / 2 - 1
  ### Scale of Sigma
  sigSca <- c(sum((n[,1] - mu[1] * n[, lim + 1])^2),
              colSums((n[, 2:(lim + 1)] - t(mu[2:(lim + 1)] * t(n[, 1:lim])))^2)) / 2
  ### Samples from a Gamma Distribution
  sigma  <- rgamma(n = lim + 1, shape = sigSha, rate = sigSca)
  sigma  <- 1 / sigma
  ## Stores sigma
  ss[sam,] <- sigma
}
```

```{r Plot Estimated Cases}
# Probability of Ocurrance
qua <- apply(X = sn[,,lim + 1], MARGIN = 2, FUN = quantile, probs = seq(0, 0.99, 0.01))
# Cases with probability
acc <- qua
for(i in 1:99){
  acc[i + 1, ] = qua[i + 1, ] - qua[i, ]
}
acc <- round(acc)

dates <- newDat[order(FECHA_INGRESO), FECHA_INGRESO]
newDat <- cbind(dates, data.frame(t(acc)))
colnames(newDat) <- c("date", seq(99,0))
newDat <- data.table(newDat)
newDat <- melt(newDat, id.vars = c("date"))
newDat$variable <- as.numeric(as.character(newDat$variable))
newDat <- newDat[, ]
```

```{r First Forecast}
datPlo <- newDat[order(-variable)  & date > "2020-01-01"]
ggplot(data = datPlo,
       mapping = aes(x = date, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = position_stack(reverse = TRUE))   +
  scale_fill_gradient(low = "white", high = "#F8766D") +
  ggtitle("Estimacion de Pruebas  por Fecha de Ingreso") +
  xlab("Fecha de Ingreso")  +
  ylab("Casos") +
  theme_bw()
```
