---
title:  "Modelo Casos Sospechosos"
author: "Rene Gutierrez"
date:   "5/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(data.table)
library(ggplot2)
```

### Coronavisrus Tracker Mexico

# Analisis

## Modelo de Asignacion de Casos Sospechosos

```{r First Simulation}
### Number of Siulations
sim <- 10000
### Data
datAna <- dataMex[, .N, by = .(FECHA_INGRESO, RESULTADO)]
datAna <- datAna[order(RESULTADO)]
datAna <- dcast(datAna, FECHA_INGRESO ~ RESULTADO)
datAna <- as.matrix(datAna[, -1])
datAna <- cbind(datAna, rowSums(datAna, na.rm = TRUE))
datAna[is.na(datAna)] <- 0
### Data Size
m <- nrow(datAna)
k <- datAna[, 1]
z <- datAna[, 3]
n <- datAna[, 4]

### Samples Storage
sy <- matrix(data = NA,
             nrow = sim,
             ncol = m)
st <- numeric(sim)

### Initializes Theta
t <-  sum(k) / sum(n)
y <- numeric(m)

### For Each Simulation
for(s in 1:sim){
  ### Samples y
  for(i in 1:m){
    ### Checks if there is anythig to sample
    if(z[i] == 0){
      y[i] <- k[i]
    } else {
      ### Computes the probability of each extra case
      pro <- dbinom(x = k[i]:(k[i] + z[i]), size = n[i], prob = t, log = TRUE)
      pro <- exp(pro - max(pro))
      pro <- pro / sum(pro)
      ### Samples y
      y[i] <- sample(x = k[i]:(k[i] + z[i]), size = 1, replace = TRUE, prob = pro)
    }
    ### Stores y
    sy[s, i] <- y[i]
  }
  # Samples theta
  ## Parameters Beta Distribution
  sha1 <- sum(y) + 1
  sha2 <- sum(n) - sum(y) + 1
  ## Samples theta
  t <- rbeta(n = 1, shape1 = sha1, shape2 = sha2)
  ## Stores theta
  st[i] <- t
}
```

```{r Plot Estimated Cases}
# Probability of Ocurrance
qua <- apply(X = sy, MARGIN = 2, FUN = quantile, probs = seq(0, 1, 0.01))
# Cases with probability
acc <- qua
for(i in 1:100){
  acc[i + 1, ] = qua[i + 1, ] - qua[i, ]
}
acc <- round(acc)

dates <- dataMex[, .N, by = FECHA_INGRESO][order(FECHA_INGRESO), FECHA_INGRESO]
newDat <- cbind(dates, data.frame(t(acc)))
colnames(newDat) <- c("date", seq(100,0))
newDat <- data.table(newDat)
newDat <- melt(newDat, id.vars = c("date"))
newDat$variable <- as.numeric(as.character(newDat$variable))
newDat <- newDat[, ]
```

```{r First Forecast}
datPlo <- newDat[order(-variable)  & date > "2020-01-01"]
ggplot(data = datPlo,
       mapping = aes(x = date, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = position_stack(reverse = TRUE))   +
  scale_fill_gradient(low = "white", high = "#F8766D") +
  ggtitle("Estimacion de Casos por Fecha de Ingreso") +
  xlab("Fecha de Ingreso")  +
  ylab("Casos") +
  theme_bw()
```

```{r First Forecast (JNSD)}
datPlo <- newDat[order(variable)]
datPlo <- newDat[date > "2020-03-23"]
ggplot(data = datPlo,
       mapping = aes(x = date, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = position_stack(reverse = TRUE))   +
  scale_fill_gradient(low = "white", high = "#F8766D") +
  ggtitle("Estimacion de Positivos por Fecha de Ingreso (JNSD)") +
  xlab("Fecha de Ingreso")  +
  ylab("Casos") +
  theme_bw()
```
